# Generated by Django 3.2.7 on 2021-09-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_subsubtopic_subtopic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubtopic',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.subtopic'),
        ),
    ]
